includes coronal models for emissivity profiles
astro-group-bristol/Gradus.jl pull request #138
Opened 2023-08-02 11:02 UTC by wiktoriatarnopolska

ready to merge, includes new AbstractType -- Abstract CoronalModels and exposed the emissivity profile function to the photon index parameter.

2023-08-02 11:39 UTC, fjebaker commented on src/Gradus.jl
> +"""
Docstring here is missing

2023-08-02 11:39 UTC, fjebaker commented on src/corona/emissivity.jl
> +function source_to_disc_emissivity(
Docstring for this function needs updating

2023-08-02 11:39 UTC, fjebaker commented on src/corona/emissivity.jl
> +point_source_equitorial_disc_emissivity(spec::AbstractCoronalSpectrum, θ, g, A, γ) =
Docstring for this function needs updating

2023-08-02 11:39 UTC, fjebaker commented on src/corona/spectra.jl
> +"""
Missing docstring

2023-08-02 11:39 UTC, fjebaker commented on test/smoke-tests/coronal-spectra.jl
> +)
Missing some explicit numerical tests. The simplest you can do is make sure it's working right, then do a low-resolution calculation and ensure that it is always able to reproduce that (see some of the other tests for examples).

2023-08-02 11:40 UTC, fjebaker commented
There's a few missing docstrings here and there that would be good to update as part of this PR. Likewise, the test cases are still needing to do a numerical comparison, to make sure we don't accidentally break known results.

If you're keen to do this, let me know, else I'll add a few commits that address these last few points :)

2023-08-15 19:28 UTC, wiktoriatarnopolska commented on src/Gradus.jl
> +"""
done now!

2023-08-20 09:55 UTC, fjebaker requested changes
Looking good! Just a few little changes still needed + some test cases :)

2023-08-20 09:55 UTC, fjebaker commented on src/corona/emissivity.jl
> +    source_to_disc_emissivity(m, N, A, x, g)
This function signature needs updating.

2023-08-20 09:55 UTC, fjebaker commented on src/corona/emissivity.jl
> +of 'spectrum' and 'g' since it is defined as 'g^Γ' so passing the spectrum as an argument allows their further modification.
This is good, but should be in the docstring for `PowerLawSpectrum`, since it is specific to that spectrum.

2023-08-20 09:55 UTC, fjebaker commented on src/corona/spectra.jl
> +    g^(spectrum.Γ)
This needs to be $g^{-\Gamma}$, since coronal spectrum defines $I$ and we then compute

$$
\varepsilon = \frac{N  I}{ A \gamma}
$$

2023-08-20 09:55 UTC, fjebaker commented on src/corona/emissivity.jl
> +    point_source_equitorial_disc_emissivity(θ, g, A, γ, spectrum)
Function signature needs updating.

2023-08-22 13:58 UTC, fjebaker commented on src/corona/emissivity.jl
> +The ratio of energies is ``g`` (computed with [`energy_ratio`](@ref)), with ``spec`` being the abstract
Here should be single backticks for `spec`, else it will format as $spec$.

2023-08-22 13:58 UTC, fjebaker commented on src/corona/spectra.jl
> +Spectrum for the power law simply returns the photon index 'Γ'. 'I' stores the 'coronal_spectrum' which is a function
These should be \`, not ' so that it code formats :)

2023-08-22 14:07 UTC, fjebaker requested changes

2023-08-22 14:53 UTC, merged